//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATO
    {
        public System.Guid ORID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string FOTO { get; set; }
        public System.Guid POSTULACION { get; set; }
    
        public virtual POSTULACION POSTULACION1 { get; set; }
    }
}
