//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCRUTINIO_CAB
    {
        public System.Guid ORID { get; set; }
        public System.Guid MESA { get; set; }
        public int VOTOS_EMITIDOS { get; set; }
        public int SOBRES { get; set; }
        public System.TimeSpan INICIO { get; set; }
        public System.TimeSpan FIN { get; set; }
        public System.Guid USUARIO { get; set; }
    
        public virtual MESA MESA1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
