//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCRUTINIO_MESA
    {
        public System.Guid ORID { get; set; }
        public System.Guid MESA { get; set; }
        public System.Guid CARGO { get; set; }
        public int NULOS { get; set; }
        public int RECURRIDOS { get; set; }
        public int IMPUGNADOS { get; set; }
        public int BLANCOS { get; set; }
        public int VALIDOS { get; set; }
        public Nullable<int> TOTALES { get; set; }
    
        public virtual MESA MESA1 { get; set; }
        public virtual CARGO CARGO1 { get; set; }
    }
}
