//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESCRUTINIOEntities : DbContext
    {
        public ESCRUTINIOEntities()
            : base("name=ESCRUTINIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGRUPACION> AGRUPACION { get; set; }
        public virtual DbSet<CANDIDATO> CANDIDATO { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CIRCUITO> CIRCUITO { get; set; }
        public virtual DbSet<ESCRUTINIO_CAB> ESCRUTINIO_CAB { get; set; }
        public virtual DbSet<ESCRUTINIO_DET> ESCRUTINIO_DET { get; set; }
        public virtual DbSet<ESCRUTINIO_MESA> ESCRUTINIO_MESA { get; set; }
        public virtual DbSet<ESCUELA> ESCUELA { get; set; }
        public virtual DbSet<MESA> MESA { get; set; }
        public virtual DbSet<POSTULACION> POSTULACION { get; set; }
        public virtual DbSet<REGLA> REGLA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<TIPO_VOTO> TIPO_VOTO { get; set; }
        public virtual DbSet<vwCircuitosExtranjeros> vwCircuitosExtranjeros { get; set; }
        public virtual DbSet<vwEscuelasExtranjeras> vwEscuelasExtranjeras { get; set; }
        public virtual DbSet<vwEscuelasNacionales> vwEscuelasNacionales { get; set; }
        public virtual DbSet<LISTA> LISTA { get; set; }
    }
}
