//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCUELA
    {
        public ESCUELA()
        {
            this.MESA = new HashSet<MESA>();
        }
    
        public System.Guid ORID { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DIRECCION { get; set; }
        public string LATITUD { get; set; }
        public string LONGITUD { get; set; }
        public string CONTACTO { get; set; }
        public string LOCALIDAD { get; set; }
        public System.Guid CIRCUITO { get; set; }
        public int CANT_MESAS { get; set; }
        public bool PRIVADA { get; set; }
    
        public virtual CIRCUITO CIRCUITO1 { get; set; }
        public virtual ICollection<MESA> MESA { get; set; }
    }
}
