//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA
    {
        public LISTA()
        {
            this.POSTULACION = new HashSet<POSTULACION>();
        }
    
        public System.Guid ORID { get; set; }
        public int NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public System.Guid AGRUPACION { get; set; }
        public int ORDEN { get; set; }
        public string CODE { get; set; }
    
        public virtual AGRUPACION AGRUPACION1 { get; set; }
        public virtual ICollection<POSTULACION> POSTULACION { get; set; }
    }
}
