//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.ESCRUTINIO_CAB = new HashSet<ESCRUTINIO_CAB>();
            this.ESCRUTINIO_DET = new HashSet<ESCRUTINIO_DET>();
            this.ESCRUTINIO_MESA = new HashSet<ESCRUTINIO_MESA>();
        }
    
        public System.Guid ORID { get; set; }
        public int NUMERO { get; set; }
        public int CANT_VOTANTES { get; set; }
        public bool EXTRANJERO { get; set; }
        public string PRESIDENTE { get; set; }
        public string VICEPRESIDENTE { get; set; }
        public string FISCAL { get; set; }
        public System.Guid ESCUELA { get; set; }
    
        public virtual ICollection<ESCRUTINIO_CAB> ESCRUTINIO_CAB { get; set; }
        public virtual ICollection<ESCRUTINIO_DET> ESCRUTINIO_DET { get; set; }
        public virtual ICollection<ESCRUTINIO_MESA> ESCRUTINIO_MESA { get; set; }
        public virtual ESCUELA ESCUELA1 { get; set; }
    }
}
