//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTULACION
    {
        public POSTULACION()
        {
            this.CANDIDATO = new HashSet<CANDIDATO>();
            this.ESCRUTINIO_DET = new HashSet<ESCRUTINIO_DET>();
        }
    
        public System.Guid ORID { get; set; }
        public System.Guid LISTA { get; set; }
        public System.Guid CARGO { get; set; }
    
        public virtual ICollection<CANDIDATO> CANDIDATO { get; set; }
        public virtual CARGO CARGO1 { get; set; }
        public virtual ICollection<ESCRUTINIO_DET> ESCRUTINIO_DET { get; set; }
        public virtual LISTA LISTA1 { get; set; }
    }
}
