//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.REGLA = new HashSet<REGLA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public System.Guid ORID { get; set; }
        public string DESCRIPCION { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual ICollection<REGLA> REGLA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
