//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrutinio.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ESCRUTINIO_CAB = new HashSet<ESCRUTINIO_CAB>();
            this.ROL = new HashSet<ROL>();
        }
    
        public System.Guid ORID { get; set; }
        public string USUARIO1 { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string TELEFONO { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<ESCRUTINIO_CAB> ESCRUTINIO_CAB { get; set; }
        public virtual ICollection<ROL> ROL { get; set; }
    }
}
